
name: Pack Servico + Push no NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pack-push:
    env:
      PROJECT_PATH: ./FiscalCore.Servicos/FiscalCore.Servicos.csproj

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup FiscalCore.Servicos
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Packet generator
      run: dotnet pack ${{ env.PROJECT_PATH }} -c Release -o out

    - name: Push to NuGet
      run: >
        dotnet nuget push out/*.nupkg
        --api-key ${{ secrets.FISCALCORE_SERVICOS_API_KEY }}
        --source https://api.nuget.org/v3/index.json
        --skip-duplicate
